import time
import math
user_is_old = 0
print("                ....................................................                                     .+******++++++========------:::::::::::............................     ")
print("    .#%%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.                                     .#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#.     ")
print("     .*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%-.                                     ..:*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*.       ")
print("     ..:%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@=...   .-++=--:::...       .---:........     ..=@@@@@@@@%####%%%%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@=..        ")
print("        .+@@@%%%%%%####***++===--::...  ....::---==+*#%@@@@@@#.      .=@@==@@@@@%*:        .-*@@@@@@@%:       .:@@@@@@@@@@@@@@@@@%%##++==--:::....         .....:::-:.           ")
print("                       ..:-=+*#%@@@@@@@@@@@@@@@@@@@@@@@@@@@@=..      .:.+@@@@@@:=*.        :%%:*@@@%::+:.       :@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%#*+=--..                ")
print("           .=%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%#+--=*#@@@@@#.     :#@@@@*..=%#.%@@@%-. .:*@@@@@-@@+-%@@@@@.     :@@@@@@@#+=-=+#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*..             ")
print("              *@@@@@@@@@@@@@@@@@@@@@%#*=-...-=*%@@@@@@@@@@@*.     .:#@.      .#@@@@@@= -@@@@@@%:=-.   .#%..     -@@@@@@@@@@@@@@%*=-::-=+*#%@@@@@@@@@@@@@@@@@@@@*.                ")
print("              ..#@@@@@@@@@@%*-........-*@@@@@@@@@@@@@@@@@@@#.      ..:.      ..-@@@@*.*.+@@@@-......  ...     ..@@@@@@@+.-#@@@@@@@@@@@@@%*-......-+#@@@@@@@@@*.                  ")
print("               ..:+-::........:=*%@@@@@@@@@@@@@@@@#=-+@@@@@@#..          ...=#%:.*@%.+@#.#@+..#@@%#=.........:*@@@@@@@@@@@%*:.-+@@@@@@@@@@@@@@@@%#*=:.....::..                   ")
print("                      .:=*%@@@@@@@@@@@@@@@@@@#+:.-#@@@@@@@@@@@+:.    .-=*@@@@@@@*.-:=@@@= ..*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%+-..-+%@@@@@@@@@@@@@@@@@@%-.                      ")
print("                    .-@@@@@@@@@@@@@@@@@@@*:...=@@@@@@@#+@@@@@@@@@@@@@@@@@@@@@@@@@@::%@@@%.-@@@@@@@@@@@@@@@@@@@@@@@@@@%-+@@@@@@@@@@@#:...:+%@@@@@@@@@@@@+..                       ")
print("                      .:%@@@@@@@@@@@*:....:#@@@@@@@@=-@@@@@@@@@@@@@@@@@@@@@@*@@@@*.#@@@@@#.*@@@@#*@@@@@@@@@@@@@@@@@@@@@@=.=@@@@@@@@@@@@%=....:=%@@@@@=..                         ")
print("                         :%@@@@*=:.  ..+%@@@@@@@@#::#@@@@@*@@@@@@@@@@@@@@@@*-@@@@.+@@@@@@@=.%@@%.#@@*@@@@@@@@@@@@@@+@@@@@@+.:+%@@@@@@@@@@@@%+:.  .:-..                           ")
print("                          .....  ..:*@@@@@@@@@@*..*@@@@@%=@@@@%=%@@@%@@@:%**@@@@--@@@@@@@@%::@@@%:%*.@@@=@@@@*=@@@@%:*@@@@@@*...+@@@@@@@@@@@@@@@+.                               ")
print("                              ..=@@@@@@@@@@@@=..+@@@@@@+:@@@@%.+@@@-#@@@..#@@@@+.%@@@@@@@@@#.+@@@*..:@@@=+@@@@=#@@@@@-:@@@@@@@%....+@@@@@@@@@@%...                               ")
print("                                -%@@@@@@@@%-..=@@@@@@@--@@@@@-:@@@%.%@@#:%@@@@%.#@@@@@@@@@@@+.%@@@#.:@@@=:@@@@%:%@@@@@-.+@@@@@@@%-  .:+@@@@@*..                                  ")
print("                                 .:#@@@@*...:%@@@@@@*.=@@@@@=.%@@@+.%@--@@@@@@.=@@@@@@@@@@@@@::@@@@%:.=@+.#@@@@+:@@@@@@+.:%@@@@@@@@=.. ..+=..                                    ")
print("                                    .*=  ..%@@@@@@@:.=@@@@@*.=@@@@:.= -@@@@@@=.@@@@@@@@@@@@@@#.=@@@@@+....+@@@@@:=@@@@@@+. -@@@@@@@@@+..                                         ")
print("                                        .*@@@@@@@%..=@@@@@%..@@@@#.     .=@@*.%@@@@@@@@@@@@@@@+.%@@*:     =@@@@@%.+@@@@@@#. .#@@@@@@@+:.                                         ")
print("                                        ..-#@@@@=..+@@@@@%..#@@@+..      ....*@@@@@@@@@@@@@@@@@-.:..      ..:+#@@=.*@@@@@@#...-@@%+..                                            ")
print("                                            .:*...*@@@@@@-.=@*.             -@@@@@@@@@@@@@@@@@@%.                 .:@@@@@@@%.                                                    ")
print("                                                ..:::=+#= .:.               .+@@@@@@@@@@@@@@@@@@-                                                                                ")
print("                                                                          .-%-.=@@@@@@@@@@@@@@=:#-.                                                                              ")
print("                                                                         .:@@@@-.@@@@@@@@@@@%:*@@@-.                                                                             ")
print("                                                                         .@@@@::%@#@@@@@@@%@@%.=@@@-                                                                             ")
print("                                                                  ......:%@@@-.#@=#@*@@@%@#*@@%..%@@*:...++.                                                                     ")
print("                                                                  .@@@@@@@@@:.#@+=@%+@@@+@@-%@@+..%@@@@@@@*.                                                                     ")
print("                                                                  .#@=-%@@@@#.+#.@@=%@@@=%@#-#...-@@@@%-%@=                                                                      ")
print("                                                                  .=-.*@@+%@@#..-@*=@@@@#-@#...+%@@@=+@*.%-                                                                      ")
print("                                                                   ..%@@-.%@*.   ..@@@@@%...   .=#@@=:=@*:.                                                                      ")
print("                                                                  ..#@%. =:.       :@@@@:.        ..+#.-@@=.                                                                     ")
print("                                                                  .-@@#. ..        ..*+..            #%@@@*.                                                                     ")
print("                                                                   ..-==:.                                                                                                       ")
time.sleep(10)
user_firstname = input("Who are you? First name please. ")
user_nameSpace = " "
user_lastname = input("and your last name please. ")
user_name = (user_firstname + user_nameSpace + user_lastname)
Name_length = len(user_name)
if user_name == "Trey Lemons":
    print("Hello", user_name, "Of Mckinleyville")
else:
    print("Hello",user_name, "of Cis 12")
print("you have",Name_length, " Charcaters in your name")
time.sleep(1)
print("I can talk in lower and upper case as well")
scream = "ahhh"
uppercase_string = scream.upper()
time.sleep(1)
print(uppercase_string)
time.sleep(1)
lowercase_string = scream.lower()
print(lowercase_string)
time.sleep(1)
print("Make sure to please the machine spirit during programming")
time.sleep(0.5)
print("Or lose all your progress")
time.sleep(1)
print("I wanna know more about you since you and i are gonna be with each other for a while")
time.sleep(1)
user_age_str = input("How old are you? ")
user_age = int(user_age_str)
if user_age >= 50:
    print("Ha!")
    time.sleep(1)
    print("Old!")
    user_is_old = 1
    time.sleep(1)
else:
    print("cool")
if user_is_old == 1:
    user_heigh_str = input("alright alright i'm sorry, what about your height in feet? I won't make fun of you. ")
else:
    user_heigh_str = input("ok, now how tall are you in feet?")
user_heigh = int(user_heigh_str)
time.sleep(1)
print("Wow, so your ", user_heigh_str, " feet Tall.")
time.sleep(1)
user_weight_str = input("how about how big you are? like your weight.")
time.sleep(1)
print(user_weight_str)
user_weight = int(user_weight_str)
time.sleep(0.5)
print("Alright, not bothering to look at that rn")
time.sleep(1)
print("Doing Math")
user_BMI = user_weight // user_heigh
time.sleep(1)
print(user_BMI)
time.sleep(1)
print("wanna do some fun stuff?")
time.sleep(0.5)
print("No? too bad we're doing math")
time.sleep(1)
Circle_radius = input("enter the radius of the circle ")
try:
    radius = float(Circle_radius)
except ValueError:
        print("You use numbers, not words, can't do math with words")
        exit()
area = math.pi * (radius ** 2)
print("The area of the circle is with radius ", radius, " is: ", area)
radius = 3
vol_sphere = 4/3 * math.pi * radius ** 3
print(vol_sphere)